export default {
  Server: [
    {
      key: 'Render to string',
      numberOfSamples: 1,
      samples: [2.9],
      minValue: 2.9,
      maxValue: 2.9,
      meanValue: 2.9,
      medianValue: 2.9,
    },
    {
      key: 'Render to static markup (cannot be hydrated)',
      numberOfSamples: 1,
      samples: [2.2],
      minValue: 2.2,
      maxValue: 2.2,
      meanValue: 2.2,
      medianValue: 2.2,
    },
    {
      key: 'String output size',
      numberOfSamples: 1,
      samples: [1.9],
      minValue: 1.9,
      maxValue: 1.9,
      meanValue: 1.9,
      medianValue: 1.9,
    },
    {
      key: 'String output size (gzip)',
      numberOfSamples: 1,
      samples: [0.15],
      minValue: 0.15,
      maxValue: 0.15,
      meanValue: 0.15,
      medianValue: 0.15,
    },
    {
      key: 'Static markup output size',
      numberOfSamples: 1,
      samples: [1.9],
      minValue: 1.9,
      maxValue: 1.9,
      meanValue: 1.9,
      medianValue: 1.9,
    },
    {
      key: 'Static markup output size (gzip)',
      numberOfSamples: 1,
      samples: [0.15],
      minValue: 0.15,
      maxValue: 0.15,
      meanValue: 0.15,
      medianValue: 0.15,
    },
  ],
  Client: [
    {
      key: 'Initial render',
      numberOfSamples: 1,
      samples: [2.8],
      minValue: 2.8,
      maxValue: 2.8,
      meanValue: 2.8,
      medianValue: 2.8,
    },
    {
      key: 'Re render',
      numberOfSamples: 1,
      samples: [0.3],
      minValue: 0.3,
      maxValue: 0.3,
      meanValue: 0.3,
      medianValue: 0.3,
    },
    {
      key: 'Hydrate',
      numberOfSamples: 1,
      samples: [1.8],
      minValue: 1.8,
      maxValue: 1.8,
      meanValue: 1.8,
      medianValue: 1.8,
    },
    {
      key: 'Complete render (mount + layout + paint)',
      numberOfSamples: 1,
      samples: [4.8],
      minValue: 4.8,
      maxValue: 4.8,
      meanValue: 4.8,
      medianValue: 4.8,
    },
    {
      key: 'DOM element count',
      numberOfSamples: 1,
      samples: [40],
      minValue: 40,
      maxValue: 40,
      meanValue: 40,
      medianValue: 40,
    },
    {
      key: 'DOM element count (no nested inline svg elements)',
      numberOfSamples: 1,
      samples: [40],
      minValue: 40,
      maxValue: 40,
      meanValue: 40,
      medianValue: 40,
    },
    {
      key: 'React Fiber node count',
      numberOfSamples: 1,
      samples: [181],
      minValue: 181,
      maxValue: 181,
      meanValue: 181,
      medianValue: 181,
    },
  ],
  Interactions: [
    {
      key: 'Click a menu item',
      numberOfSamples: 1,
      samples: [0.7],
      minValue: 0.7,
      maxValue: 0.7,
      meanValue: 0.7,
      medianValue: 0.7,
    },
    {
      key: 'Focus on a menu item',
      numberOfSamples: 1,
      samples: [0],
      minValue: 0,
      maxValue: 0,
      meanValue: 0,
      medianValue: 0,
    },
    {
      key: 'Select a menu item',
      numberOfSamples: 1,
      samples: [0.7],
      minValue: 0.7,
      maxValue: 0.7,
      meanValue: 0.7,
      medianValue: 0.7,
    },
    {
      key: 'Disable a menu item',
      numberOfSamples: 1,
      samples: [0.5],
      minValue: 0.5,
      maxValue: 0.5,
      meanValue: 0.5,
      medianValue: 0.5,
    },
  ],
};
