name: Cypress browser tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  browser-test:
    name: Cypress browser tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install yarn + our dependencies
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      # Build the addon so it can be used
      - run: yarn workspaces run build
      # Okay, finally start cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          working-directory: packages/storybook-addon-performance
          start: yarn run storybook:dev
          wait-on: 'http://localhost:9003'
          wait-on-timeout: 120
      # Upload the videos and screenshots
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        # We want to upload the recording even if the last step failed
        # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
        if: always()
        with:
          name: cypress-videos
          path: /packages/storybook-addon-performance/cypress/videos
